# Generated by Django 5.2.14 on 2026-07-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(default='TEMP-PART', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='parts.category'),
        ),
        migrations.AlterField(
            model_name='part',
            name='compatible_model',
            field=models.CharField(help_text='Example: BMW F10 520d', max_length=100),
        ),
    ]
